"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[▸▹ ](dimmed white)"


format = """
$os\
[](fg:widget_os_bg_color bg:widget_directory_bg_color)\
$directory\
[](fg:widget_directory_bg_color bg:widget_git_bg_color)\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
[](fg:widget_git_bg_color bg:widget_toolchain_bg_color)\
$nodejs\
$bun\
$rust\
$golang\
$php\
$python\
$docker_context\
$conda\
[](fg:widget_toolchain_bg_color)\
[ ]()\
$fill\
[  ]()\
$battery\
$sudo\
$jobs\
$cmd_duration\
[](fg:widget_time_bg_color)\
[ $time  ](bg:widget_time_bg_color fg:widget_time_fg_color)\
\n$character"""

add_newline = true

palette = 'peter'

# right_format = """
# $battery\
# [](fg:widget_time_bg_color)\
# [ $time  ](bg:widget_time_bg_color fg:widget_time_fg_color)\
# \n"""

[fill]
symbol = '·'
style = 'fg:#444444'

[jobs]
symbol = '+'
number_threshold = 2
symbol_threshold = 1

[cmd_duration]
min_time = 500
format = """\
[](fg:widget_duration_bg_color)\
[󱦟 $duration](bg:widget_duration_bg_color fg:widget_duration_fg_color)\
[](fg:widget_duration_bg_color)\
[ ]()\
"""

[sudo]
style = 'bold green'
format = '[$symbol]($style)'
symbol = '   '
disabled = false

[directory]
style = "fg:widget_directory_fg_color bg:widget_directory_bg_color"
format = "[$read_only $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = " ~"

[git_branch]
symbol = ""
style = "bg:widget_git_bg_color"
format = '[[ $symbol $branch ](fg:widget_git_fg_color bg:widget_git_bg_color)]($style)'

[git_status]
style = "bg:widget_git_bg_color"
format = '[[($all_status$ahead_behind )](fg:widget_git_fg_color bg:widget_git_bg_color)]($style)'

[git_commit]
disabled = false
style = "bg:widget_git_bg_color"
commit_hash_length = 4
format = '[[\($hash$tag\)](fg:widget_git_fg_color bg:widget_git_bg_color) ]($style)'
tag_symbol = '󰓹 '

[git_metrics]
disabled = false
added_style = "fg:widget_git_fg_color bg:widget_git_bg_color"
deleted_style = "fg:widget_git_fg_color bg:widget_git_bg_color"
format = '[[+$added]($added_style)/[-$deleted]($deleted_style)](fg:widget_git_fg_color bg:widget_git_bg_color)'

[nodejs]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol ($version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[bun]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol ($version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[c]
symbol = " "
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol( $version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[rust]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol ($version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[python]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol( $version)(\($virtualenv\)) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[docker_context]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol( $context) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[conda]
symbol = "  "
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol( $environment) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'
ignore_base = false

[golang]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol ($version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[java]
symbol = " "
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol( $version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[kotlin]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol( $version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[php]
symbol = ""
style = "bg:widget_toolchain_bg_color"
format = '[[ $symbol ($version) ](fg:widget_toolchain_fg_color bg:widget_toolchain_bg_color)]($style)'

[character]
success_symbol = "[❯](bold character_success_color)"
error_symbol = "[❯](bold character_error_color)"

[time]
disabled = false
utc_time_offset = "local"
time_format = "%R" # Hour:Minute Format
format = '$time '
# style = "bg:widget_time_bg_color fg:widget_time_fg_color"
# format = '[$time ]($style)'

[os]
style = "bg:widget_os_bg_color fg:widget_os_fg_color"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[palettes.peter]
character_success_color = "#80D440"
character_error_color = "#C83323"
widget_time_bg_color = "#DFE5EB"
widget_time_fg_color = "#38424B"
widget_os_bg_color = "#DFE5EB"
widget_os_fg_color = "#090c0c"
widget_directory_bg_color = "#769ff0"
widget_directory_fg_color = "#e3e5e5"
widget_git_bg_color = "#394260"
widget_git_fg_color = "#769ff0"
widget_toolchain_bg_color = "#212736"
widget_toolchain_fg_color = "#769ff0"
widget_duration_bg_color = "yellow"
widget_duration_fg_color = "#090c0c"
